# Dependencies
gems:             [jekyll-paginate, jekyll-gist]
markdown:         kramdown
kramdown:
  math_engine:     mathjax
#markdown:         kramdown
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Intro Data Science
tagline:          'A first course for engineers, planners and social scientists'
description:      'A project funded by <a href="http://nitc.trec.pdx.edu" target="_blank">NITC</a>'
url:              http://cities.github.io/
baseurl:          /datascience/

author:
  name:           'Liming Wang'
  url:            'http://web.pdx.edu/~limwang'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cities/datascience
