# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Intro Data Science
tagline:          'A first course for engineers, planners and social scientists'
description:      'A project funded by <a href="http://nitc.trec.pdx.edu" target="_blank">NITC</a>'
url:              http://cities.github.io/datascience
baseurl:          /

author:
  name:           'Liming Wang'
  url:            'http://web.pdx.edu/~limwang'

paginate:         5
gems:             [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cities/datascience
